# Redirect HTTP → HTTPS
server {
    listen 80;
    server_name japan-fest.my.id www.japan-fest.my.id admin.japan-fest.my.id api.japan-fest.my.id;


    # Certbot ACME challenge
    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}

# Falcon
server {
    listen 443 ssl;
    server_name japan-fest.my.id www.japan-fest.my.id;

    ssl_certificate     /etc/letsencrypt/live/japan-fest.my.id/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/japan-fest.my.id/privkey.pem;
    include             /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam         /etc/letsencrypt/ssl-dhparams.pem;

    client_max_body_size 10M;

    location / {
        proxy_pass         http://falcon:3000;
        proxy_http_version 1.1;
        proxy_set_header   Upgrade $http_upgrade;
        proxy_set_header   Connection 'upgrade';
        proxy_set_header   Host $host;
        proxy_set_header   X-Real-IP $remote_addr;
        proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto $scheme;
        proxy_cache_bypass $http_upgrade;
    }
}

# Dolphin
server {
    listen 443 ssl;
    server_name admin.japan-fest.my.id;

    ssl_certificate     /etc/letsencrypt/live/japan-fest.my.id/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/japan-fest.my.id/privkey.pem;
    include             /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam         /etc/letsencrypt/ssl-dhparams.pem;

    client_max_body_size 10M;

    location / {
        proxy_pass         http://dolphin:3001;
        proxy_http_version 1.1;
        proxy_set_header   Upgrade $http_upgrade;
        proxy_set_header   Connection 'upgrade';
        proxy_set_header   Host $host;
        proxy_set_header   X-Real-IP $remote_addr;
        proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto $scheme;
        proxy_cache_bypass $http_upgrade;
    }
}

# Phoenix
server {
    listen 443 ssl;
    server_name api.japan-fest.my.id;

    ssl_certificate     /etc/letsencrypt/live/japan-fest.my.id/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/japan-fest.my.id/privkey.pem;
    include             /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam         /etc/letsencrypt/ssl-dhparams.pem;

    client_max_body_size 20M;

    location / {
        proxy_pass         http://phoenix:3000;
        proxy_http_version 1.1;
        proxy_set_header   Upgrade $http_upgrade;
        proxy_set_header   Connection 'upgrade';
        proxy_set_header   Host $host;
        proxy_set_header   X-Real-IP $remote_addr;
        proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto $scheme;
        proxy_cache_bypass $http_upgrade;
    }
}
